import type { ProfessorReviewPublicRow } from "@/lib/professor-reviews/types";
import type { CalendarEvent, Course } from "@/lib/types";

// Real schedule data from 2026-05-04 week (Mon-Sat)
// Extracted from horario-2026-05-10.ics
const weekStart = new Date(2026, 4, 4); // Monday May 4, 2026

function eventDate(weekday: number, time: string): Date {
  const dayOffset = weekday === 0 ? 6 : weekday - 1;
  const d = new Date(weekStart);
  d.setDate(d.getDate() + dayOffset);
  const [hours, minutes] = time.split(":").map(Number);
  d.setHours(hours, minutes, 0, 0);
  return d;
}

export const demoCalendarEvents: CalendarEvent[] = [
  {
    id: "MA1403-02-20260505T093000",
    title: "MATEMÁTICA DISCRETA",
    courseName: "MATEMÁTICA DISCRETA",
    courseCode: "MA1403",
    groupCode: "02",
    groupId: "MA1403-02",
    groupType: "REGULAR",
    professors: [{ id: 1, name: "CHAVARRIA MOLINA JEFFRY" }],
    classroom: "D3-11",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "violet",
    start: eventDate(2, "09:30"),
    end: eventDate(2, "11:20"),
    courseId: "MA1403",
    group: 2,
    credits: 3,
  },
  {
    id: "IC1802-05-20260506T073000",
    title: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    courseName: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    courseCode: "IC1802",
    groupCode: "05",
    groupId: "IC1802-05",
    groupType: "SEMIPRESENCIAL",
    professors: [{ id: 1, name: "MATA RODRIGUEZ WILLIAM" }],
    classroom: "B6-02",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "orange",
    start: eventDate(3, "07:30"),
    end: eventDate(3, "09:20"),
    courseId: "IC1802",
    group: 5,
    credits: 3,
  },
  {
    id: "IC1803-05-20260506T093000",
    title: "TALLER DE PROGRAMACIÓN",
    courseName: "TALLER DE PROGRAMACIÓN",
    courseCode: "IC1803",
    groupCode: "05",
    groupId: "IC1803-05",
    groupType: "SEMIPRESENCIAL",
    professors: [{ id: 1, name: "MATA RODRIGUEZ WILLIAM" }],
    classroom: "B6-05",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "fuchsia",
    start: eventDate(3, "09:30"),
    end: eventDate(3, "11:20"),
    courseId: "IC1803",
    group: 5,
    credits: 3,
  },
  {
    id: "CI1106-23-20260507T130000",
    title: "COMUNICACIÓN ESCRITA",
    courseName: "COMUNICACIÓN ESCRITA",
    courseCode: "CI1106",
    groupCode: "23",
    groupId: "CI1106-23",
    groupType: "VIRTUAL",
    professors: [{ id: 1, name: "ROMERO ALVAREZ ERICKA" }],
    classroom: null,
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "yellow",
    start: eventDate(4, "13:00"),
    end: eventDate(4, "15:50"),
    courseId: "CI1106",
    group: 23,
    credits: 3,
  },
  {
    id: "MA1403-02-20260507T093000",
    title: "MATEMÁTICA DISCRETA",
    courseName: "MATEMÁTICA DISCRETA",
    courseCode: "MA1403",
    groupCode: "02",
    groupId: "MA1403-02",
    groupType: "REGULAR",
    professors: [{ id: 1, name: "CHAVARRIA MOLINA JEFFRY" }],
    classroom: "D3-11",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "violet",
    start: eventDate(4, "09:30"),
    end: eventDate(4, "11:20"),
    courseId: "MA1403",
    group: 2,
    credits: 3,
  },
  {
    id: "IC1802-05-20260508T073000",
    title: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    courseName: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    courseCode: "IC1802",
    groupCode: "05",
    groupId: "IC1802-05",
    groupType: "SEMIPRESENCIAL",
    professors: [{ id: 1, name: "MATA RODRIGUEZ WILLIAM" }],
    classroom: "B6-02",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "orange",
    start: eventDate(5, "07:30"),
    end: eventDate(5, "09:20"),
    courseId: "IC1802",
    group: 5,
    credits: 3,
  },
  {
    id: "IC1803-05-20260508T093000",
    title: "TALLER DE PROGRAMACIÓN",
    courseName: "TALLER DE PROGRAMACIÓN",
    courseCode: "IC1803",
    groupCode: "05",
    groupId: "IC1803-05",
    groupType: "SEMIPRESENCIAL",
    professors: [{ id: 1, name: "MATA RODRIGUEZ WILLIAM" }],
    classroom: "B6-05",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "fuchsia",
    start: eventDate(5, "09:30"),
    end: eventDate(5, "11:20"),
    courseId: "IC1803",
    group: 5,
    credits: 3,
  },
  {
    id: "CI1230-11-20260508T130000",
    title: "INGLÉS I",
    courseName: "INGLÉS I",
    courseCode: "CI1230",
    groupCode: "11",
    groupId: "CI1230-11",
    groupType: "VIRTUAL",
    professors: [{ id: 1, name: "HERRERA JIMENEZ INGRID" }],
    classroom: null,
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "red",
    start: eventDate(5, "13:00"),
    end: eventDate(5, "15:50"),
    courseId: "CI1230",
    group: 11,
    credits: 3,
  },
];

// Static curriculum data for course relation graph demo
// Real data from IC4301 - BASES DE DATOS I (plan 48, Ingeniería en Computación 2022)
export const demoRelationCourse: Course = {
  id: "IC4301",
  code: "IC4301",
  name: "BASES DE DATOS I",
  credits: 4,
  hours: 9,
  semester: 3,
  status: "not_taken",
  prerequisites: ["IC2001"],
  corequisites: ["MA1103"],
};

export const demoPrerequisites: Course[] = [
  {
    id: "IC2001",
    code: "IC2001",
    name: "ESTRUCTURAS DE DATOS",
    credits: 4,
    hours: 12,
    semester: 2,
    status: "not_taken",
    prerequisites: ["IC1802", "IC1803"],
    corequisites: [],
  },
];

export const demoCorequisites: Course[] = [
  {
    id: "MA1103",
    code: "MA1103",
    name: "CÁLCULO Y ÁLGEBRA LINEAL",
    credits: 4,
    hours: 4,
    semester: 3,
    status: "not_taken",
    prerequisites: ["MA1102"],
    corequisites: [],
  },
];

export const demoDependents: Course[] = [
  {
    id: "IC4302",
    code: "IC4302",
    name: "BASES DE DATOS II",
    credits: 3,
    hours: 9,
    semester: 4,
    status: "not_taken",
    prerequisites: ["IC4301"],
    corequisites: [],
  },
];

// Static professor review data for landing page demo
export const demoReviewRows: ProfessorReviewPublicRow[] = [
  {
    review_id: 1,
    professor_id: "1178",
    courses: [
      {
        id: 1037,
        code: "IC1400",
        name: "FUNDAMENTOS DE ORGANIZACIÓN DE COMPUTADORAS",
      },
    ],
    comment:
      "El profesor explica muy bien los fundamentos de bases de datos relacionales. Los laboratorios son prácticos y ayudan a entender SQL. Eso sí, los exámenes son largos y hay que estudiar bastante.",
    ease_score: 6.5,
    quality_score: 9.0,
    clarity_score: 8.5,
    fairness_score: 8.0,
    attendance_required: false,
    grade_received: "85",
    engagement_level: 4,
    tags: ["Explica con claridad", "Proyecto útil", "Exámenes retadores"],
    status: "approved",
    created_at: "2026-03-15T14:30:00Z",
    like_count: 12,
    dislike_count: 2,
    my_reaction: null,
    total_count: 3,
  },
  {
    review_id: 2,
    professor_id: "1192",
    courses: [
      {
        id: 1038,
        code: "IC3101",
        name: "ARQUITECTURA DE COMPUTADORES",
      },
    ],
    comment:
      "Muy buen profesor, siempre dispuesto a ayudar. Las clases son interactivas y el proyecto final integra todo lo visto durante el semestre. Recomiendo llevar el curso con él.",
    ease_score: 7.0,
    quality_score: 9.5,
    clarity_score: 9.0,
    fairness_score: 9.0,
    attendance_required: true,
    grade_received: "92",
    engagement_level: 5,
    tags: ["Da buena retroalimentación", "Brinda apoyo", "Tomaría su clase nuevamente"],
    status: "approved",
    created_at: "2026-04-02T10:15:00Z",
    like_count: 18,
    dislike_count: 1,
    my_reaction: null,
    total_count: 3,
  },
  {
    review_id: 3,
    professor_id: "1171",
    courses: [
      {
        id: 1039,
        code: "IC4700",
        name: "LENGUAJES DE PROGRAMACIÓN",
      },
    ],
    comment:
      "Las clases son claras y bien estructuradas. El material de apoyo en el TEC Digital es completo. Los quizzes semanales ayudan a llevar el curso al día. Muy recomendada.",
    ease_score: 8.0,
    quality_score: 8.5,
    clarity_score: 9.5,
    fairness_score: 7.5,
    attendance_required: true,
    grade_received: "78",
    engagement_level: 3,
    tags: ["Explica con claridad", "Da buena retroalimentación"],
    status: "approved",
    created_at: "2026-02-20T08:00:00Z",
    like_count: 7,
    dislike_count: 3,
    my_reaction: null,
    total_count: 3,
  },
];

export const demoStudyPlanDetail: any = {
  plan: {
    id: 48,
    academic_unit_id: 10,
    external_plan_id: 412,
    name: "INGENIERÍA EN COMPUTACIÓN",
    academic_degree: "LICENCIATURA",
    modality_name: "SEMESTRAL",
  },
  periods: [
    {
      levelNumber: 0,
      levelLabel: "SEMESTRE 0",
      courses: [
        {
          courseId: 537,
          levelNumber: 0,
          credits: 0,
          weeklyHours: 0,
          sortOrder: 0,
          courseCode: "CI0200",
          courseName: "EXAMEN DIAGNÓSTICO",
          courseDefaultCredits: 0,
          courseDefaultWeeklyHours: 0,
        },
        {
          courseId: 539,
          levelNumber: 0,
          credits: 2,
          weeklyHours: 3,
          sortOrder: 10,
          courseCode: "CI0202",
          courseName: "INGLÉS BÁSICO",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 3,
        },
        {
          courseId: 563,
          levelNumber: 0,
          credits: 2,
          weeklyHours: 5,
          sortOrder: 20,
          courseCode: "MA0101",
          courseName: "MATEMÁTICA GENERAL",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 5,
        },
      ],
    },
    {
      levelNumber: 1,
      levelLabel: "SEMESTRE 1",
      courses: [
        {
          courseId: 554,
          levelNumber: 1,
          credits: 2,
          weeklyHours: 6,
          sortOrder: 0,
          courseCode: "CI1106",
          courseName: "COMUNICACIÓN ESCRITA",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 6,
        },
        {
          courseId: 1017,
          levelNumber: 1,
          credits: 3,
          weeklyHours: 9,
          sortOrder: 10,
          courseCode: "IC1400",
          courseName: "FUNDAMENTOS DE ORGANIZACIÓN DE COMPUTADORAS",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 9,
        },
        {
          courseId: 1020,
          levelNumber: 1,
          credits: 3,
          weeklyHours: 4,
          sortOrder: 20,
          courseCode: "IC1802",
          courseName: "INTRODUCCIÓN A LA PROGRAMACIÓN",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1022,
          levelNumber: 1,
          credits: 3,
          weeklyHours: 4,
          sortOrder: 30,
          courseCode: "IC1803",
          courseName: "TALLER DE PROGRAMACIÓN",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1018,
          levelNumber: 1,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 40,
          courseCode: "MA1403",
          courseName: "MATEMÁTICA DISCRETA",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 497,
          levelNumber: 1,
          credits: 0,
          weeklyHours: 2,
          sortOrder: 50,
          courseCode: "SE1100",
          courseName: "ACTIVIDAD CULTURAL I",
          courseDefaultCredits: 0,
          courseDefaultWeeklyHours: 2,
        },
      ],
    },
    {
      levelNumber: 2,
      levelLabel: "SEMESTRE 2",
      courses: [
        {
          courseId: 600,
          levelNumber: 2,
          credits: 1,
          weeklyHours: 3,
          sortOrder: 0,
          courseCode: "CI1107",
          courseName: "COMUNICACIÓN ORAL",
          courseDefaultCredits: 1,
          courseDefaultWeeklyHours: 3,
        },
        {
          courseId: 545,
          levelNumber: 2,
          credits: 2,
          weeklyHours: 6,
          sortOrder: 10,
          courseCode: "CI1230",
          courseName: "INGLÉS I",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 6,
        },
        {
          courseId: 648,
          levelNumber: 2,
          credits: 0,
          weeklyHours: 2,
          sortOrder: 20,
          courseCode: "FH1000",
          courseName: "CENTROS DE FORMACIÓN HUMANÍSTICA",
          courseDefaultCredits: 0,
          courseDefaultWeeklyHours: 2,
        },
        {
          courseId: 1029,
          levelNumber: 2,
          credits: 4,
          weeklyHours: 12,
          sortOrder: 30,
          courseCode: "IC2001",
          courseName: "ESTRUCTURAS DE DATOS",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 12,
        },
        {
          courseId: 1030,
          levelNumber: 2,
          credits: 3,
          weeklyHours: 9,
          sortOrder: 40,
          courseCode: "IC2101",
          courseName: "PROGRAMACIÓN ORIENTADA A OBJETOS",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 9,
        },
        {
          courseId: 1032,
          levelNumber: 2,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 50,
          courseCode: "IC3101",
          courseName: "ARQUITECTURA DE COMPUTADORES",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 605,
          levelNumber: 2,
          credits: 4,
          weeklyHours: 5,
          sortOrder: 60,
          courseCode: "MA1102",
          courseName: "CÁLCULO DIFERENCIAL E INTEGRAL",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 5,
        },
        {
          courseId: 490,
          levelNumber: 2,
          credits: 0,
          weeklyHours: 2,
          sortOrder: 70,
          courseCode: "SE1200",
          courseName: "ACTIVIDAD DEPORTIVA I",
          courseDefaultCredits: 0,
          courseDefaultWeeklyHours: 2,
        },
      ],
    },
    {
      levelNumber: 3,
      levelLabel: "SEMESTRE 3",
      courses: [
        {
          courseId: 625,
          levelNumber: 3,
          credits: 2,
          weeklyHours: 3,
          sortOrder: 0,
          courseCode: "CI1231",
          courseName: "INGLÉS II",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 3,
        },
        {
          courseId: 1035,
          levelNumber: 3,
          credits: 4,
          weeklyHours: 12,
          sortOrder: 10,
          courseCode: "IC3002",
          courseName: "ANÁLISIS DE ALGORITMOS",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 12,
        },
        {
          courseId: 1037,
          levelNumber: 3,
          credits: 4,
          weeklyHours: 9,
          sortOrder: 20,
          courseCode: "IC4301",
          courseName: "BASES DE DATOS I",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 9,
        },
        {
          courseId: 1039,
          levelNumber: 3,
          credits: 4,
          weeklyHours: 12,
          sortOrder: 30,
          courseCode: "IC5821",
          courseName: "REQUERIMIENTOS DE SOFTWARE",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 12,
        },
        {
          courseId: 634,
          levelNumber: 3,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 40,
          courseCode: "MA1103",
          courseName: "CÁLCULO Y ÁLGEBRA LINEAL",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 647,
          levelNumber: 3,
          credits: 0,
          weeklyHours: 2,
          sortOrder: 50,
          courseCode: "SE1400",
          courseName: "ACTIVIDAD CULTURAL-DEPORTIVA",
          courseDefaultCredits: 0,
          courseDefaultWeeklyHours: 2,
        },
      ],
    },
    {
      levelNumber: 4,
      levelLabel: "SEMESTRE 4",
      courses: [
        {
          courseId: 628,
          levelNumber: 4,
          credits: 2,
          weeklyHours: 6,
          sortOrder: 0,
          courseCode: "CS2101",
          courseName: "AMBIENTE HUMANO",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 6,
        },
        {
          courseId: 1043,
          levelNumber: 4,
          credits: 3,
          weeklyHours: 9,
          sortOrder: 10,
          courseCode: "IC4302",
          courseName: "BASES DE DATOS II",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 9,
        },
        {
          courseId: 1045,
          levelNumber: 4,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 20,
          courseCode: "IC4700",
          courseName: "LENGUAJES DE PROGRAMACIÓN",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1047,
          levelNumber: 4,
          credits: 4,
          weeklyHours: 12,
          sortOrder: 30,
          courseCode: "IC6821",
          courseName: "DISEÑO DE SOFTWARE",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 12,
        },
        {
          courseId: 1049,
          levelNumber: 4,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 40,
          courseCode: "MA2404",
          courseName: "PROBABILIDADES",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
      ],
    },
    {
      levelNumber: 5,
      levelLabel: "SEMESTRE 5",
      courses: [
        {
          courseId: 981,
          levelNumber: 5,
          credits: 2,
          weeklyHours: 3,
          sortOrder: 0,
          courseCode: "CS3401",
          courseName: "SEMINARIO DE ESTUDIOS FILOSÓFICOS HISTÓRICOS",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 3,
        },
        {
          courseId: 1052,
          levelNumber: 5,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 10,
          courseCode: "IC4810",
          courseName: "ADMINISTRACIÓN DE PROYECTOS",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1054,
          levelNumber: 5,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 20,
          courseCode: "IC5701",
          courseName: "COMPILADORES E INTERPRETES",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1056,
          levelNumber: 5,
          credits: 3,
          weeklyHours: 9,
          sortOrder: 30,
          courseCode: "IC6831",
          courseName: "ASEGURAMIENTO DE LA CALIDAD DEL SOFTWARE",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 9,
        },
        {
          courseId: 1057,
          levelNumber: 5,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 40,
          courseCode: "MA3405",
          courseName: "ESTADÍSTICA",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
      ],
    },
    {
      levelNumber: 6,
      levelLabel: "SEMESTRE 6",
      courses: [
        {
          courseId: 1004,
          levelNumber: 6,
          credits: 2,
          weeklyHours: 3,
          sortOrder: 0,
          courseCode: "CS4402",
          courseName: "SEMINARIO DE ESTUDIOS COSTARRICENSES",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 3,
        },
        {
          courseId: 1059,
          levelNumber: 6,
          credits: 3,
          weeklyHours: 4,
          sortOrder: 10,
          courseCode: "IC4003",
          courseName: "ELECTIVA I",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1151,
          levelNumber: 6,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 20,
          courseCode: "IC6400",
          courseName: "INVESTIGACIÓN DE OPERACIONES",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1154,
          levelNumber: 6,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 30,
          courseCode: "IC6600",
          courseName: "PRINCIPIOS DE SISTEMAS OPERATIVOS",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1156,
          levelNumber: 6,
          credits: 2,
          weeklyHours: 7,
          sortOrder: 40,
          courseCode: "IC7900",
          courseName: "COMPUTACIÓN Y SOCIEDAD",
          courseDefaultCredits: 2,
          courseDefaultWeeklyHours: 7,
        },
        {
          courseId: 1158,
          levelNumber: 6,
          credits: 3,
          weeklyHours: 9,
          sortOrder: 50,
          courseCode: "IC8071",
          courseName: "SEGURIDAD DEL SOFTWARE",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 9,
        },
      ],
    },
    {
      levelNumber: 7,
      levelLabel: "SEMESTRE 7",
      courses: [
        {
          courseId: 965,
          levelNumber: 7,
          credits: 4,
          weeklyHours: 12,
          sortOrder: 0,
          courseCode: "AE4208",
          courseName: "DESARROLLO DE EMPRENDEDORES",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 12,
        },
        {
          courseId: 1160,
          levelNumber: 7,
          credits: 3,
          weeklyHours: 4,
          sortOrder: 10,
          courseCode: "IC5001",
          courseName: "ELECTIVA II",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1162,
          levelNumber: 7,
          credits: 4,
          weeklyHours: 4,
          sortOrder: 20,
          courseCode: "IC6200",
          courseName: "INTELIGENCIA ARTIFICIAL",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 4,
        },
        {
          courseId: 1163,
          levelNumber: 7,
          credits: 4,
          weeklyHours: 12,
          sortOrder: 30,
          courseCode: "IC7602",
          courseName: "REDES",
          courseDefaultCredits: 4,
          courseDefaultWeeklyHours: 12,
        },
        {
          courseId: 1159,
          levelNumber: 7,
          credits: 3,
          weeklyHours: 9,
          sortOrder: 40,
          courseCode: "IC7841",
          courseName: "PROYECTO DE INGENIERÍA DE SOFTWARE",
          courseDefaultCredits: 3,
          courseDefaultWeeklyHours: 9,
        },
      ],
    },
    {
      levelNumber: 8,
      levelLabel: "SEMESTRE 8",
      courses: [
        {
          courseId: 1166,
          levelNumber: 8,
          credits: 12,
          weeklyHours: 40,
          sortOrder: 0,
          courseCode: "IC8842",
          courseName: "PRÁCTICA PROFESIONAL",
          courseDefaultCredits: 12,
          courseDefaultWeeklyHours: 40,
        },
      ],
    },
  ],
  courseRelations: new Map([
    [491, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [492, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [493, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [494, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [495, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [496, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [574, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [575, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [576, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [577, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [578, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [579, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [580, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [581, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [582, { prerequisites: [], corequisites: [], equivalents: [490] }],
    [583, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [584, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [585, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [586, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [587, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [588, { prerequisites: [], corequisites: [], equivalents: [490] }],
    [589, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [590, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [591, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [592, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [593, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [594, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [595, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [596, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [597, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [598, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [599, { prerequisites: [], corequisites: [], equivalents: [490, 647] }],
    [498, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [499, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [500, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [501, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [502, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [503, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [504, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [505, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [506, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [507, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [508, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [509, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [510, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [511, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [512, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [513, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [619, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [620, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [621, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [622, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [623, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [624, { prerequisites: [], corequisites: [], equivalents: [497, 647] }],
    [135, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [538, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [539, { prerequisites: [545], corequisites: [], equivalents: [537] }],
    [540, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [541, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [542, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [543, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [544, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [545, { prerequisites: [625], corequisites: [], equivalents: [537, 539] }],
    [546, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [547, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [548, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [549, { prerequisites: [], corequisites: [], equivalents: [537, 539, 545] }],
    [550, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [551, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [552, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [553, { prerequisites: [], corequisites: [], equivalents: [537, 539] }],
    [537, { prerequisites: [545], corequisites: [], equivalents: [539] }],
    [555, { prerequisites: [], corequisites: [], equivalents: [554] }],
    [556, { prerequisites: [], corequisites: [], equivalents: [554] }],
    [554, { prerequisites: [600], corequisites: [], equivalents: [] }],
    [563, { prerequisites: [605], corequisites: [], equivalents: [] }],
    [1018, { prerequisites: [605], corequisites: [1017], equivalents: [] }],
    [1034, { prerequisites: [], corequisites: [], equivalents: [605] }],
    [627, { prerequisites: [], corequisites: [], equivalents: [625] }],
    [600, { prerequisites: [628], corequisites: [], equivalents: [] }],
    [1042, { prerequisites: [], corequisites: [], equivalents: [628] }],
    [605, { prerequisites: [634, 1035], corequisites: [], equivalents: [] }],
    [1041, { prerequisites: [], corequisites: [], equivalents: [634] }],
    [490, { prerequisites: [1166], corequisites: [], equivalents: [647] }],
    [497, { prerequisites: [1166], corequisites: [], equivalents: [647] }],
    [618, { prerequisites: [], corequisites: [], equivalents: [647] }],
    [649, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [650, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [651, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [652, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [653, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [654, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [655, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [656, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [657, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [658, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [659, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [660, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [661, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [662, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [663, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [664, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [665, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [666, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [667, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [668, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [669, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [670, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [671, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [672, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [673, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [674, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [675, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [676, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [677, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [678, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [679, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [680, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [681, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [682, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [683, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [684, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [685, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [686, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [687, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [688, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [689, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [690, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [691, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [692, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [693, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [694, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [695, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [696, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [697, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [698, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [699, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [700, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [701, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [702, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [703, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [704, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [705, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [706, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [707, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [708, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [709, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [710, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [711, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [712, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [713, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [714, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [715, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [716, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [717, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [718, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [719, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [720, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [721, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [722, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [723, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [724, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [725, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [726, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [727, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [728, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [729, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [730, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [731, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [732, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [733, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [734, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [735, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [736, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [737, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [738, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [739, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [740, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [741, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [742, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [743, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [744, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [745, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [746, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [747, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [748, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [749, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [750, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [751, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [752, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [753, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [754, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [755, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [756, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [757, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [758, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [759, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [760, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [761, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [762, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [763, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [764, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [765, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [766, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [767, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [768, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [769, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [770, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [771, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [772, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [773, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [774, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [775, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [776, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [777, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [778, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [779, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [780, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [781, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [782, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [783, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [784, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [785, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [786, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [787, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [788, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [789, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [790, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [791, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [792, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [793, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [794, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [795, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [796, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [797, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [798, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [799, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [800, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [801, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [802, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [803, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [804, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [805, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [806, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [807, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [808, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [809, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [810, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [811, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [812, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [813, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [814, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [815, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [816, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [817, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [818, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [819, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [820, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [821, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [822, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [823, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [824, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [825, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [826, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [827, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [828, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [829, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [830, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [831, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [832, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [833, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [834, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [835, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [836, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [837, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [838, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [839, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [840, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [841, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [842, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [843, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [844, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [845, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [846, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [847, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [848, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [849, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [850, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [851, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [852, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [853, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [854, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [855, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [856, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [857, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [858, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [859, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [860, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [861, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [862, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [863, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [864, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [865, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [866, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [867, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [868, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [869, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [870, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [871, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [872, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [873, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [874, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [875, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [876, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [877, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [878, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [879, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [880, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [881, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [882, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [883, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [884, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [885, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [886, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [887, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [888, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [889, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [890, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [891, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [892, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [893, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [894, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [895, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [896, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [897, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [898, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [899, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [900, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [901, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [902, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [903, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [904, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [905, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [906, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [907, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [908, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [909, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [910, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [911, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [912, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [913, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [914, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [915, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [916, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [917, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [918, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [919, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [920, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [921, { prerequisites: [], corequisites: [], equivalents: [648] }],
    [966, { prerequisites: [], corequisites: [], equivalents: [965] }],
    [967, { prerequisites: [], corequisites: [], equivalents: [965] }],
    [1159, { prerequisites: [1166], corequisites: [965], equivalents: [] }],
    [628, { prerequisites: [981], corequisites: [], equivalents: [] }],
    [1051, { prerequisites: [], corequisites: [], equivalents: [981] }],
    [981, { prerequisites: [1004], corequisites: [], equivalents: [] }],
    [1005, { prerequisites: [], corequisites: [], equivalents: [1004] }],
    [1019, { prerequisites: [], corequisites: [], equivalents: [1017] }],
    [1024, { prerequisites: [], corequisites: [], equivalents: [1018] }],
    [1025, { prerequisites: [], corequisites: [], equivalents: [1018] }],
    [1026, { prerequisites: [], corequisites: [], equivalents: [1018] }],
    [1027, { prerequisites: [], corequisites: [], equivalents: [1018] }],
    [1028, { prerequisites: [], corequisites: [], equivalents: [1018] }],
    [1021, { prerequisites: [], corequisites: [], equivalents: [1020] }],
    [1023, { prerequisites: [], corequisites: [], equivalents: [1022] }],
    [1030, { prerequisites: [], corequisites: [1029], equivalents: [] }],
    [1031, { prerequisites: [], corequisites: [], equivalents: [1029] }],
    [1020, { prerequisites: [1030], corequisites: [], equivalents: [] }],
    [1022, { prerequisites: [1030, 1032], corequisites: [], equivalents: [] }],
    [1017, { prerequisites: [1032], corequisites: [], equivalents: [] }],
    [1033, { prerequisites: [], corequisites: [], equivalents: [1032] }],
    [1029, { prerequisites: [1035, 1037], corequisites: [], equivalents: [] }],
    [1036, { prerequisites: [], corequisites: [], equivalents: [1035] }],
    [634, { prerequisites: [1049], corequisites: [1037], equivalents: [] }],
    [1038, { prerequisites: [], corequisites: [], equivalents: [1037] }],
    [1037, { prerequisites: [1043], corequisites: [1039], equivalents: [] }],
    [1040, { prerequisites: [], corequisites: [], equivalents: [1039] }],
    [1044, { prerequisites: [], corequisites: [], equivalents: [1043] }],
    [1032, { prerequisites: [1045], corequisites: [], equivalents: [] }],
    [1035, { prerequisites: [1045], corequisites: [], equivalents: [] }],
    [1046, { prerequisites: [], corequisites: [], equivalents: [1045] }],
    [1039, { prerequisites: [1047, 1052], corequisites: [], equivalents: [] }],
    [1048, { prerequisites: [], corequisites: [], equivalents: [1047] }],
    [1050, { prerequisites: [], corequisites: [], equivalents: [1049] }],
    [1053, { prerequisites: [], corequisites: [], equivalents: [1052] }],
    [1045, { prerequisites: [1054], corequisites: [], equivalents: [] }],
    [1055, { prerequisites: [], corequisites: [], equivalents: [1054] }],
    [1047, { prerequisites: [1056], corequisites: [], equivalents: [] }],
    [1052, { prerequisites: [1156, 1158], corequisites: [1056], equivalents: [] }],
    [1049, { prerequisites: [1057], corequisites: [], equivalents: [] }],
    [1058, { prerequisites: [], corequisites: [], equivalents: [1057] }],
    [1060, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1061, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1062, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1063, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1064, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1065, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1066, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1067, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1068, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1069, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1070, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1071, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1072, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1073, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1074, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1075, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1076, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1077, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1078, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1079, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1080, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1081, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1082, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1083, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1084, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1085, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1086, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1087, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1088, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1089, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1090, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1091, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1092, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1093, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1094, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1095, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1096, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1097, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1098, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1099, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1100, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1101, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1102, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1103, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1104, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1105, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1106, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1107, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1108, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1109, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1110, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1111, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1112, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1113, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1114, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1115, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1116, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1117, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1118, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1119, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1120, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1121, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1122, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1123, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1124, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1125, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1126, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1127, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1128, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1129, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1130, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1131, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1132, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1133, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1134, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1135, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1136, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1137, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1138, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1139, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1140, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1141, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1142, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1143, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1144, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1145, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1146, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1147, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1148, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1149, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1150, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [4932, { prerequisites: [], corequisites: [], equivalents: [1059, 1160] }],
    [1057, { prerequisites: [1151], corequisites: [], equivalents: [] }],
    [1152, { prerequisites: [], corequisites: [], equivalents: [1151] }],
    [1153, { prerequisites: [], corequisites: [], equivalents: [1151] }],
    [1054, { prerequisites: [1154, 1162], corequisites: [], equivalents: [] }],
    [1155, { prerequisites: [], corequisites: [], equivalents: [1154] }],
    [1004, { prerequisites: [], corequisites: [1156], equivalents: [] }],
    [1157, { prerequisites: [], corequisites: [], equivalents: [1156] }],
    [1056, { prerequisites: [1158, 1159], corequisites: [], equivalents: [] }],
    [1043, { prerequisites: [1159], corequisites: [], equivalents: [] }],
    [1158, { prerequisites: [1159], corequisites: [], equivalents: [] }],
    [1165, { prerequisites: [], corequisites: [], equivalents: [1159] }],
    [1161, { prerequisites: [], corequisites: [], equivalents: [1160] }],
    [1151, { prerequisites: [1162], corequisites: [], equivalents: [] }],
    [1154, { prerequisites: [1163], corequisites: [], equivalents: [] }],
    [1164, { prerequisites: [], corequisites: [], equivalents: [1163] }],
    [647, { prerequisites: [1166], corequisites: [], equivalents: [] }],
    [648, { prerequisites: [1166], corequisites: [], equivalents: [] }],
    [965, { prerequisites: [1166], corequisites: [], equivalents: [] }],
    [1059, { prerequisites: [1166], corequisites: [], equivalents: [] }],
    [1160, { prerequisites: [1166], corequisites: [], equivalents: [] }],
    [1162, { prerequisites: [1166], corequisites: [], equivalents: [] }],
    [1163, { prerequisites: [1166], corequisites: [], equivalents: [] }],
    [1167, { prerequisites: [], corequisites: [], equivalents: [1166] }],
  ]),
};
