packages:
  - "apps/*"

engineStrict: true
minimumReleaseAge: 72
publicHoistPattern:
  - "pdfjs-dist"

allowBuilds:
  "@parcel/watcher": true
  "@prisma/client": true
  better-sqlite3: true
  esbuild: true
  sharp: false
  simple-git-hooks: true
  supabase: true
  workerd: true

auditConfig:
  ignoreGhsas:
    - GHSA-rmmr-r34h-pfm5
