-- ============================================================================
-- TEC-DATA DELTA SEED
-- ============================================================================
-- TEC-DATA-META environment_id=127.0.0.1|postgres
-- TEC-DATA-META scope=catalog
-- TEC-DATA-META years=2020,2021,2022,2023,2024,2025,2026
-- TEC-DATA-META term_external_keys=2020_A_1,2020_B_1,2020_B_2,2020_B_3,2020_B_4,2020_B_5,2020_B_6,2020_B_7,2020_C_1,2020_C_2,2020_C_3,2020_H_1,2020_H_2,2020_H_3,2020_H_4,2020_H_5,2020_H_6,2020_I_1,2020_I_2,2020_M_1,2020_M_10,2020_M_11,2020_M_12,2020_M_2,2020_M_3,2020_M_4,2020_M_5,2020_M_6,2020_M_7,2020_M_8,2020_M_9,2020_N_1,2020_S_1,2020_S_2,2020_T_1,2020_T_2,2020_T_3,2020_T_4,2020_V_1,2021_A_1,2021_B_1,2021_B_2,2021_B_3,2021_B_4,2021_B_5,2021_B_6,2021_B_7,2021_C_1,2021_C_2,2021_C_3,2021_H_1,2021_H_2,2021_H_3,2021_H_4,2021_H_5,2021_H_6,2021_I_1,2021_I_2,2021_M_1,2021_M_10,2021_M_11,2021_M_12,2021_M_2,2021_M_3,2021_M_4,2021_M_5,2021_M_6,2021_M_7,2021_M_8,2021_M_9,2021_N_1,2021_S_1,2021_S_2,2021_T_1,2021_T_2,2021_T_3,2021_T_4,2021_V_1,2022_A_1,2022_B_1,2022_B_2,2022_B_3,2022_B_4,2022_B_5,2022_B_6,2022_B_7,2022_C_1,2022_C_2,2022_C_3,2022_H_1,2022_H_2,2022_H_3,2022_H_4,2022_H_5,2022_H_6,2022_I_1,2022_I_2,2022_M_1,2022_M_10,2022_M_11,2022_M_12,2022_M_2,2022_M_3,2022_M_4,2022_M_5,2022_M_6,2022_M_7,2022_M_8,2022_M_9,2022_N_1,2022_S_1,2022_S_2,2022_T_1,2022_T_2,2022_T_3,2022_T_4,2022_V_1,2023_A_1,2023_B_1,2023_B_2,2023_B_3,2023_B_4,2023_B_5,2023_B_6,2023_B_7,2023_C_1,2023_C_2,2023_C_3,2023_H_1,2023_H_2,2023_H_3,2023_H_4,2023_H_5,2023_H_6,2023_I_1,2023_I_2,2023_M_1,2023_M_10,2023_M_11,2023_M_12,2023_M_2,2023_M_3,2023_M_4,2023_M_5,2023_M_6,2023_M_7,2023_M_8,2023_M_9,2023_N_1,2023_S_1,2023_S_2,2023_T_1,2023_T_2,2023_T_3,2023_T_4,2023_V_1,2024_A_1,2024_B_1,2024_B_2,2024_B_3,2024_B_4,2024_B_5,2024_B_6,2024_B_7,2024_C_1,2024_C_2,2024_C_3,2024_H_1,2024_H_2,2024_H_3,2024_H_4,2024_H_5,2024_H_6,2024_I_1,2024_I_2,2024_M_1,2024_M_10,2024_M_11,2024_M_12,2024_M_2,2024_M_3,2024_M_4,2024_M_5,2024_M_6,2024_M_7,2024_M_8,2024_M_9,2024_N_1,2024_S_1,2024_S_2,2024_T_1,2024_T_2,2024_T_3,2024_T_4,2024_V_1,2025_A_1,2025_B_1,2025_B_2,2025_B_3,2025_B_4,2025_B_5,2025_B_6,2025_B_7,2025_C_1,2025_C_2,2025_C_3,2025_H_1,2025_H_2,2025_H_3,2025_H_4,2025_H_5,2025_H_6,2025_I_1,2025_I_2,2025_M_1,2025_M_10,2025_M_11,2025_M_12,2025_M_2,2025_M_3,2025_M_4,2025_M_5,2025_M_6,2025_M_7,2025_M_8,2025_M_9,2025_N_1,2025_S_1,2025_S_2,2025_T_1,2025_T_2,2025_T_3,2025_T_4,2025_V_1,2026_A_1,2026_B_1,2026_B_2,2026_B_3,2026_B_4,2026_B_5,2026_B_6,2026_B_7,2026_C_1,2026_C_2,2026_C_3,2026_H_1,2026_H_2,2026_H_3,2026_H_4,2026_H_5,2026_H_6,2026_I_1,2026_I_2,2026_M_1,2026_M_10,2026_M_11,2026_M_12,2026_M_2,2026_M_3,2026_M_4,2026_M_5,2026_M_6,2026_M_7,2026_M_8,2026_M_9,2026_N_1,2026_S_1,2026_S_2,2026_T_1,2026_T_2,2026_T_3,2026_T_4,2026_V_1
-- TEC-DATA-META data_fingerprint=518cc2d42a7149052bcaa7ca1810836822972e58bfc84ef5b41814d2fb5f63f4
-- TEC-DATA-META generated_at_utc=2026-07-07T07:25:29.980843+00:00

BEGIN;
SET LOCAL TIME ZONE 'UTC';

-- table: study_plan
UPDATE public.study_plan SET name = E'BACHILLERATO EN ARQUITECTURA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 340;
UPDATE public.study_plan SET is_active = FALSE, deactivated_at = NOW(), updated_at = NOW() WHERE id = ANY(ARRAY[4]::BIGINT[]);

-- table: study_plan_campus
INSERT INTO public.study_plan_campus
  (id, study_plan_id, campus_id, valid_from, valid_to)
VALUES
  (665, 317, 22, NULL, NULL),
  (666, 199, 22, NULL, NULL),
  (667, 200, 22, NULL, NULL),
  (668, 201, 22, NULL, NULL),
  (669, 206, 22, NULL, NULL)
ON CONFLICT (study_plan_id, campus_id) DO UPDATE SET valid_from = EXCLUDED.valid_from, valid_to = EXCLUDED.valid_to, is_active = TRUE, deactivated_at = NULL, updated_at = NOW();
UPDATE public.study_plan_campus SET is_active = FALSE, deactivated_at = NOW(), updated_at = NOW() WHERE id = ANY(ARRAY[11, 14, 16, 17, 18, 24, 27, 36, 38, 41, 42, 52, 58, 63, 65, 73, 77, 81, 88, 92, 97, 103, 106, 121, 126, 131, 133, 139, 141, 149, 155, 157, 160, 170, 171, 174, 178, 194, 197, 199, 200, 205, 219, 220, 222, 225, 227, 233, 240, 243, 250, 251, 252, 260, 261, 264, 266, 267, 275, 278, 279, 292, 296, 297, 298, 301, 306, 316, 320, 324, 328, 329, 331, 332, 346, 350, 352, 355, 359, 361, 362, 363, 370, 374, 378, 379, 381, 390, 398, 400, 406, 411, 414, 415, 427, 433, 455, 456, 457, 464, 467, 468, 476, 480, 484, 485, 489, 494, 497, 498, 499, 502, 508, 514, 528, 533, 542, 547, 552, 553, 565, 566, 570, 573, 575, 576, 587, 596, 597, 599, 600, 603, 611, 612, 613, 614, 615, 628, 639, 640, 643, 656, 657, 662]::BIGINT[]);

-- table: study_plan_level
UPDATE public.study_plan_level SET is_active = FALSE, deactivated_at = NOW(), updated_at = NOW() WHERE id = ANY(ARRAY[14, 15, 16, 17, 18, 19, 20, 21, 22]::BIGINT[]);

-- table: course
UPDATE public.course SET name = E'LE1502', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 523;
UPDATE public.course SET name = E'LE1504', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 525;
UPDATE public.course SET name = E'SE1204', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 492;
UPDATE public.course SET name = E'SE1205', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 493;
UPDATE public.course SET name = E'SE1206', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 494;
UPDATE public.course SET name = E'SE1219', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 495;
UPDATE public.course SET name = E'SE1101', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 498;
UPDATE public.course SET name = E'SE1102', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 499;
UPDATE public.course SET name = E'SE1103', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 500;
UPDATE public.course SET name = E'SE1104', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 501;
UPDATE public.course SET name = E'SE1105', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 502;
UPDATE public.course SET name = E'SE1106', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 503;
UPDATE public.course SET name = E'SE1107', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 504;
UPDATE public.course SET name = E'SE1109', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 506;
UPDATE public.course SET name = E'SE1110', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 507;
UPDATE public.course SET name = E'SE1111', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 508;
UPDATE public.course SET name = E'SE2110', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 512;
UPDATE public.course SET name = E'SE2111', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 513;
UPDATE public.course SET name = E'SE1201', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 574;
UPDATE public.course SET name = E'SE1209', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 578;
UPDATE public.course SET name = E'SE1218', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 583;
UPDATE public.course SET name = E'SE1220', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 584;
UPDATE public.course SET name = E'SE1221', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 585;
UPDATE public.course SET name = E'SE1222', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 586;
UPDATE public.course SET name = E'SE1223', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 587;
UPDATE public.course SET name = E'FH0002', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 650;
UPDATE public.course SET name = E'FH0004', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 652;
UPDATE public.course SET name = E'FH0005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 653;
UPDATE public.course SET name = E'FH0010', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 658;
UPDATE public.course SET name = E'FH0011', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 659;
UPDATE public.course SET name = E'FH0015', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 663;
UPDATE public.course SET name = E'FH0016', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 664;
UPDATE public.course SET name = E'FH0024', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 672;
UPDATE public.course SET name = E'FH0025', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 673;
UPDATE public.course SET name = E'FH0029', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 677;
UPDATE public.course SET name = E'FH0033', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 681;
UPDATE public.course SET name = E'FH0034', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 682;
UPDATE public.course SET name = E'FH0035', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 683;
UPDATE public.course SET name = E'FH0039', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 687;
UPDATE public.course SET name = E'FH0040', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 688;
UPDATE public.course SET name = E'FH0041', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 689;
UPDATE public.course SET name = E'FH0044', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 692;
UPDATE public.course SET name = E'FH0047', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 695;
UPDATE public.course SET name = E'FH0050', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 698;
UPDATE public.course SET name = E'FH0051', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 699;
UPDATE public.course SET name = E'FH0052', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 700;
UPDATE public.course SET name = E'FH0053', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 701;
UPDATE public.course SET name = E'FH0061', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 709;
UPDATE public.course SET name = E'FH0068', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 716;
UPDATE public.course SET name = E'FH0069', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 717;
UPDATE public.course SET name = E'FH0082', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 730;
UPDATE public.course SET name = E'FH0085', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 733;
UPDATE public.course SET name = E'FH0086', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 734;
UPDATE public.course SET name = E'FH0087', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 735;
UPDATE public.course SET name = E'FH0088', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 736;
UPDATE public.course SET name = E'FH0103', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 751;
UPDATE public.course SET name = E'FH0115', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 763;
UPDATE public.course SET name = E'FH0117', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 765;
UPDATE public.course SET name = E'FH0118', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 766;
UPDATE public.course SET name = E'FH0121', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 769;
UPDATE public.course SET name = E'FH0123', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 771;
UPDATE public.course SET name = E'FH0124', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 772;
UPDATE public.course SET name = E'FH0129', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 777;
UPDATE public.course SET name = E'FH0130', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 778;
UPDATE public.course SET name = E'FH0135', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 783;
UPDATE public.course SET name = E'FH0146', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 794;
UPDATE public.course SET name = E'FH0147', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 795;
UPDATE public.course SET name = E'FH0151', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 799;
UPDATE public.course SET name = E'FH0154', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 802;
UPDATE public.course SET name = E'FH0156', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 804;
UPDATE public.course SET name = E'FH0158', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 806;
UPDATE public.course SET name = E'FH0162', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 810;
UPDATE public.course SET name = E'FH0167', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 815;
UPDATE public.course SET name = E'FH0173', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 821;
UPDATE public.course SET name = E'FH0175', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 823;
UPDATE public.course SET name = E'FH0178', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 826;
UPDATE public.course SET name = E'FH0181', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 829;
UPDATE public.course SET name = E'FH0182', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 830;
UPDATE public.course SET name = E'FH0185', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 833;
UPDATE public.course SET name = E'FH0187', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 835;
UPDATE public.course SET name = E'FH0190', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 838;
UPDATE public.course SET name = E'FH0191', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 839;
UPDATE public.course SET name = E'FH0198', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 846;
UPDATE public.course SET name = E'FH0204', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 852;
UPDATE public.course SET name = E'FH0205', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 853;
UPDATE public.course SET name = E'FH0210', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 858;
UPDATE public.course SET name = E'FH0211', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 859;
UPDATE public.course SET name = E'FH0212', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 860;
UPDATE public.course SET name = E'FH0214', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 862;
UPDATE public.course SET name = E'FH0216', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 864;
UPDATE public.course SET name = E'FH0217', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 865;
UPDATE public.course SET name = E'FH0219', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 867;
UPDATE public.course SET name = E'FH0221', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 869;
UPDATE public.course SET name = E'FH0223', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 871;
UPDATE public.course SET name = E'FH0224', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 872;
UPDATE public.course SET name = E'FH0227', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 875;
UPDATE public.course SET name = E'FH0228', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 876;
UPDATE public.course SET name = E'FH0231', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 879;
UPDATE public.course SET name = E'FH0234', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 882;
UPDATE public.course SET name = E'FH0239', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 887;
UPDATE public.course SET name = E'FH0241', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 889;
UPDATE public.course SET name = E'FH0242', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 890;
UPDATE public.course SET name = E'FH0244', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 892;
UPDATE public.course SET name = E'FH0246', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 894;
UPDATE public.course SET name = E'FH0249', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 897;
UPDATE public.course SET name = E'FH0250', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 898;
UPDATE public.course SET name = E'FH0251', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 899;
UPDATE public.course SET name = E'FH0253', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 901;
UPDATE public.course SET name = E'FH0257', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 905;
UPDATE public.course SET name = E'FH0259', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 907;
UPDATE public.course SET name = E'FH0261', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 909;
UPDATE public.course SET name = E'FH0262', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 910;
UPDATE public.course SET name = E'FH0263', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 911;
UPDATE public.course SET name = E'FH0264', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 912;
UPDATE public.course SET name = E'FH0267', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 915;
UPDATE public.course SET name = E'FH0268', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 916;
UPDATE public.course SET name = E'FH0271', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 919;
UPDATE public.course SET name = E'FH0272', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 920;
UPDATE public.course SET name = E'MI5135', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 985;
UPDATE public.course SET name = E'MI5151', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 106;
UPDATE public.course SET name = E'MI5152', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 107;
UPDATE public.course SET name = E'MI5411', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 110;
UPDATE public.course SET name = E'MI6153', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 113;
UPDATE public.course SET name = E'MI6252', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 988;
UPDATE public.course SET name = E'IC8035', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1106;
UPDATE public.course SET name = E'IC8040', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1111;
UPDATE public.course SET name = E'IC8045', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1116;
UPDATE public.course SET name = E'IC8046', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1117;
UPDATE public.course SET name = E'IC8048', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1119;
UPDATE public.course SET name = E'IC8050', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1121;
UPDATE public.course SET name = E'IC8051', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1122;
UPDATE public.course SET name = E'IC8052', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1123;
UPDATE public.course SET name = E'IC8056', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1127;
UPDATE public.course SET name = E'IC8057', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1128;
UPDATE public.course SET name = E'IC8058', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1129;
UPDATE public.course SET name = E'IC8059', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1130;
UPDATE public.course SET name = E'IC8060', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1131;
UPDATE public.course SET name = E'IC8061', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1132;
UPDATE public.course SET name = E'IC8063', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1134;
UPDATE public.course SET name = E'IC8066', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1137;
UPDATE public.course SET name = E'IC8068', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1139;
UPDATE public.course SET name = E'IC8073', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1143;
UPDATE public.course SET name = E'IC8076', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1146;
UPDATE public.course SET name = E'IC8078', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1148;
UPDATE public.course SET name = E'ID5402', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1150;
UPDATE public.course SET name = E'CE5201', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1335;
UPDATE public.course SET name = E'CE5506', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1336;
UPDATE public.course SET name = E'EL5805', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1339;
UPDATE public.course SET name = E'EL5807', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1340;
UPDATE public.course SET name = E'EL5811', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1341;
UPDATE public.course SET name = E'EL5850', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1342;
UPDATE public.course SET name = E'EL5854', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1346;
UPDATE public.course SET name = E'EL5855', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1347;
UPDATE public.course SET name = E'EL5857', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1348;
UPDATE public.course SET name = E'EL5858', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1349;
UPDATE public.course SET name = E'EL5841', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1354;
UPDATE public.course SET name = E'EL5842', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1355;
UPDATE public.course SET name = E'EL5856', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1356;
UPDATE public.course SET name = E'FI4304', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1423;
UPDATE public.course SET name = E'AM2404', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 232;
UPDATE public.course SET name = E'AM2107', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 221;
UPDATE public.course SET name = E'AM2106', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 220;
UPDATE public.course SET name = E'AM2105', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 219;
UPDATE public.course SET name = E'AM2110', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 223;
UPDATE public.course SET name = E'AM2407', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 235;
UPDATE public.course SET name = E'AM3002', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 258;
UPDATE public.course SET name = E'GP2526', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 375;
UPDATE public.course SET name = E'GP2527', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 376;
UPDATE public.course SET name = E'GP2515', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 386;
UPDATE public.course SET name = E'GP2516', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 387;
UPDATE public.course SET name = E'GP2531', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 390;
UPDATE public.course SET name = E'GP2504', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 398;
UPDATE public.course SET name = E'GP2506', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 399;
UPDATE public.course SET name = E'GP2508', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 401;
UPDATE public.course SET name = E'EM3010', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1703;
UPDATE public.course SET name = E'EM3011', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1704;
UPDATE public.course SET name = E'EM1612', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1713;
UPDATE public.course SET name = E'EM4010', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1715;
UPDATE public.course SET name = E'EM4011', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1716;
UPDATE public.course SET name = E'PI4706', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1769;
UPDATE public.course SET name = E'PI5706', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1772;
UPDATE public.course SET name = E'PI5708', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1773;
UPDATE public.course SET name = E'PI5709', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1774;
UPDATE public.course SET name = E'PI5710', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1775;
UPDATE public.course SET name = E'PI5408', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1788;
UPDATE public.course SET name = E'PI5711', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1790;
UPDATE public.course SET name = E'PI5712', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1791;
UPDATE public.course SET name = E'PI5713', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1792;
UPDATE public.course SET name = E'ID5002', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1897;
UPDATE public.course SET name = E'ID5003', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1898;
UPDATE public.course SET name = E'ID5004', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1899;
UPDATE public.course SET name = E'IA4010', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2047;
UPDATE public.course SET name = E'IA5403', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2049;
UPDATE public.course SET name = E'IA5604', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2059;
UPDATE public.course SET name = E'IA5605', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2060;
UPDATE public.course SET name = E'FO4002', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2201;
UPDATE public.course SET name = E'FO4221', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2214;
UPDATE public.course SET name = E'FO4222', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2216;
UPDATE public.course SET name = E'FO3126', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2219;
UPDATE public.course SET name = E'FO3128', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2220;
UPDATE public.course SET name = E'FO4124', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2222;
UPDATE public.course SET name = E'FO4406', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2224;
UPDATE public.course SET name = E'FO4409', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2225;
UPDATE public.course SET name = E'FO4420', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2227;
UPDATE public.course SET name = E'FO4421', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2228;
UPDATE public.course SET name = E'FO4422', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2229;
UPDATE public.course SET name = E'FO4430', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2230;
UPDATE public.course SET name = E'FO4431', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2231;
UPDATE public.course SET name = E'FO4434', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2233;
UPDATE public.course SET name = E'FO4435', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2234;
UPDATE public.course SET name = E'FO4436', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2235;
UPDATE public.course SET name = E'FO4437', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2236;
UPDATE public.course SET name = E'FO4439', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2238;
UPDATE public.course SET name = E'FO5122', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2246;
UPDATE public.course SET name = E'FO4310', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2260;
UPDATE public.course SET name = E'FO4413', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2268;
UPDATE public.course SET name = E'FM6201', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2304;
UPDATE public.course SET name = E'FM6202', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2305;
UPDATE public.course SET name = E'FM6300', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2308;
UPDATE public.course SET name = E'FM6301', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2309;
UPDATE public.course SET name = E'FM6303', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2311;
UPDATE public.course SET name = E'FM6504', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2317;
UPDATE public.course SET name = E'FM6600', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2319;
UPDATE public.course SET name = E'FM6601', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2320;
UPDATE public.course SET name = E'FM6602', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2321;
UPDATE public.course SET name = E'FM6603', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2322;
UPDATE public.course SET name = E'FM6604', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2323;
UPDATE public.course SET name = E'FM6605', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2324;
UPDATE public.course SET name = E'AE3542', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2463;
UPDATE public.course SET name = E'AE3551', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2464;
UPDATE public.course SET name = E'AE3552', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2465;
UPDATE public.course SET name = E'AE3555', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2467;
UPDATE public.course SET name = E'AE4541', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2468;
UPDATE public.course SET name = E'AE4542', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2469;
UPDATE public.course SET name = E'AE4543', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2470;
UPDATE public.course SET name = E'AE4544', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2471;
UPDATE public.course SET name = E'AE4549', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2472;
UPDATE public.course SET name = E'PI1401', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2473;
UPDATE public.course SET name = E'PI1402', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2474;
UPDATE public.course SET name = E'AE4548', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2480;
UPDATE public.course SET name = E'TI8508', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2567;
UPDATE public.course SET name = E'TI8509', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2568;
UPDATE public.course SET name = E'TI8511', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2569;
UPDATE public.course SET name = E'TI8512', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2570;
UPDATE public.course SET name = E'TI8513', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2593;
UPDATE public.course SET name = E'TI8515', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2595;
UPDATE public.course SET name = E'AN7001', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2729;
UPDATE public.course SET name = E'CM5243', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2780;
UPDATE public.course SET name = E'CM5221', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2790;
UPDATE public.course SET name = E'CM5241', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2796;
UPDATE public.course SET name = E'MI6253', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2886;
UPDATE public.course SET name = E'MI6254', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2887;
UPDATE public.course SET name = E'MI6255', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2888;
UPDATE public.course SET name = E'MI6256', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2889;
UPDATE public.course SET name = E'MI6258', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2891;
UPDATE public.course SET name = E'MI6259', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2892;
UPDATE public.course SET name = E'CE5303', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2985;
UPDATE public.course SET name = E'CE5508', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2993;
UPDATE public.course SET name = E'MT8005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3007;
UPDATE public.course SET name = E'MT8008', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3075;
UPDATE public.course SET name = E'MT9005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3082;
UPDATE public.course SET name = E'MT9008', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3085;
UPDATE public.course SET name = E'MT9009', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3086;
UPDATE public.course SET name = E'SO5902', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3108;
UPDATE public.course SET name = E'SO5103', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3110;
UPDATE public.course SET name = E'BI1105', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3163;
UPDATE public.course SET name = E'FO2401', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3171;
UPDATE public.course SET name = E'AI5409', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3204;
UPDATE public.course SET name = E'AI5407', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3212;
UPDATE public.course SET name = E'AI5101', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3219;
UPDATE public.course SET name = E'AI6108', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3222;
UPDATE public.course SET name = E'AI6109', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3223;
UPDATE public.course SET name = E'AI6110', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3224;
UPDATE public.course SET name = E'AI6111', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3225;
UPDATE public.course SET name = E'AI6115', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3228;
UPDATE public.course SET name = E'AI6116', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3229;
UPDATE public.course SET name = E'IB2503', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3295;
UPDATE public.course SET name = E'IB3802', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3299;
UPDATE public.course SET name = E'IB4104', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3301;
UPDATE public.course SET name = E'IB4804', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3304;
UPDATE public.course SET name = E'IB4805', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3305;
UPDATE public.course SET name = E'IB4806', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3306;
UPDATE public.course SET name = E'IB4807', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3307;
UPDATE public.course SET name = E'IB4809', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3309;
UPDATE public.course SET name = E'IB4810', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3310;
UPDATE public.course SET name = E'IB4811', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3311;
UPDATE public.course SET name = E'IB4812', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3312;
UPDATE public.course SET name = E'IB4813', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3313;
UPDATE public.course SET name = E'IB4814', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3314;
UPDATE public.course SET name = E'IB4815', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3315;
UPDATE public.course SET name = E'IB4816', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3316;
UPDATE public.course SET name = E'BL1124', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3408;
UPDATE public.course SET name = E'BL1125', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3409;
UPDATE public.course SET name = E'BL1126', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3410;
UPDATE public.course SET name = E'BL1127', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3411;
UPDATE public.course SET name = E'BL1130', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3414;
UPDATE public.course SET name = E'BL1131', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3415;
UPDATE public.course SET name = E'BL1132', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3416;
UPDATE public.course SET name = E'BL1133', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3417;
UPDATE public.course SET name = E'LA8005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3425;
UPDATE public.course SET name = E'LA8006', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3426;
UPDATE public.course SET name = E'LA8008', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3429;
UPDATE public.course SET name = E'LA7005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3433;
UPDATE public.course SET name = E'LA7008', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3438;
UPDATE public.course SET name = E'LA6147', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3466;
UPDATE public.course SET name = E'LA6148', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3467;
UPDATE public.course SET name = E'MQ1001', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3599;
UPDATE public.course SET name = E'MM2417', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 285;
UPDATE public.course SET name = E'MM2418', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 286;
UPDATE public.course SET name = E'MM2419', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 287;
UPDATE public.course SET name = E'MB1304', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3630;
UPDATE public.course SET name = E'MB1305', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3631;
UPDATE public.course SET name = E'MB1306', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3632;
UPDATE public.course SET name = E'MB2506', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3634;
UPDATE public.course SET name = E'MB2507', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3635;
UPDATE public.course SET name = E'MI6403', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3644;
UPDATE public.course SET name = E'MI6406', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3648;
UPDATE public.course SET name = E'MI7050', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3650;
UPDATE public.course SET name = E'MI7113', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3660;
UPDATE public.course SET name = E'MI7110', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3676;
UPDATE public.course SET name = E'MI6404', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3679;
UPDATE public.course SET name = E'MI7108', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3700;
UPDATE public.course SET name = E'FM6606', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3746;
UPDATE public.course SET name = E'FM6607', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3747;
UPDATE public.course SET name = E'FM6608', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3748;
UPDATE public.course SET name = E'FM6609', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3749;
UPDATE public.course SET name = E'MC3001', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 316;
UPDATE public.course SET name = E'MC3002', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 317;
UPDATE public.course SET name = E'MC3003', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 318;
UPDATE public.course SET name = E'MC3004', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 319;
UPDATE public.course SET name = E'MC3005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 320;
UPDATE public.course SET name = E'MC3006', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 321;
UPDATE public.course SET name = E'MC3007', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 322;
UPDATE public.course SET name = E'MC3008', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 323;
UPDATE public.course SET name = E'MC3009', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 324;
UPDATE public.course SET name = E'MC3010', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 325;
UPDATE public.course SET name = E'MC8805', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 39;
UPDATE public.course SET name = E'MC8811', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 45;
UPDATE public.course SET name = E'MC8816', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 50;
UPDATE public.course SET name = E'MC8819', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 53;
UPDATE public.course SET name = E'MC8822', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 56;
UPDATE public.course SET name = E'MC8832', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 65;
UPDATE public.course SET name = E'MC8836', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 69;
UPDATE public.course SET name = E'MC8838', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 71;
UPDATE public.course SET name = E'MC8839', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 330;
UPDATE public.course SET name = E'MC8840', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 331;
UPDATE public.course SET name = E'MC8842', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 333;
UPDATE public.course SET name = E'MC8843', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 334;
UPDATE public.course SET name = E'MC8850', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 335;
UPDATE public.course SET name = E'MC8851', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 336;
UPDATE public.course SET name = E'MC8845', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3760;
UPDATE public.course SET name = E'MC8846', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3761;
UPDATE public.course SET name = E'MC8847', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3762;
UPDATE public.course SET name = E'MC8849', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3764;
UPDATE public.course SET name = E'MD3271', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3837;
UPDATE public.course SET name = E'DM0008', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3862;
UPDATE public.course SET name = E'DM0009', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3863;
UPDATE public.course SET name = E'DM0010', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3864;
UPDATE public.course SET name = E'DM0011', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3865;
UPDATE public.course SET name = E'DM0012', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3866;
UPDATE public.course SET name = E'DM0014', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3868;
UPDATE public.course SET name = E'DM0015', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3869;
UPDATE public.course SET name = E'DM0016', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3870;
UPDATE public.course SET name = E'DM0017', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3871;
UPDATE public.course SET name = E'DM0018', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3872;
UPDATE public.course SET name = E'DM0019', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3873;
UPDATE public.course SET name = E'DM0020', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3874;
UPDATE public.course SET name = E'DM0038', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3876;
UPDATE public.course SET name = E'ET8002', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3907;
UPDATE public.course SET name = E'MP6166', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3930;
UPDATE public.course SET name = E'MP6112', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3966;
UPDATE public.course SET name = E'MP6113', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3967;
UPDATE public.course SET name = E'IV3305', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4021;
UPDATE public.course SET name = E'IV3307', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4023;
UPDATE public.course SET name = E'IV5301', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4041;
UPDATE public.course SET name = E'MM1405', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4087;
UPDATE public.course SET name = E'MM1419', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4094;
UPDATE public.course SET name = E'MM2409', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4099;
UPDATE public.course SET name = E'MM2412', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4101;
UPDATE public.course SET name = E'MM2413', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4102;
UPDATE public.course SET name = E'IF6005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4136;
UPDATE public.course SET name = E'IF6007', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4137;
UPDATE public.course SET name = E'IF6008', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4138;
UPDATE public.course SET name = E'IF6010', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4140;
UPDATE public.course SET name = E'IF6011', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4141;
UPDATE public.course SET name = E'IF6012', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4142;
UPDATE public.course SET name = E'IF6013', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4143;
UPDATE public.course SET name = E'MR1302', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4166;
UPDATE public.course SET name = E'MR2512', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4169;
UPDATE public.course SET name = E'MR2514', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4171;
UPDATE public.course SET name = E'MR2515', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4172;
UPDATE public.course SET name = E'MR2516', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4173;
UPDATE public.course SET name = E'MR2517', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4174;
UPDATE public.course SET name = E'MR2519', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4176;
UPDATE public.course SET name = E'MR2529', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4186;
UPDATE public.course SET name = E'MR2533', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4190;
UPDATE public.course SET name = E'MR2534', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4191;
UPDATE public.course SET name = E'PI5802', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4246;
UPDATE public.course SET name = E'FI1106', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4270;
UPDATE public.course SET name = E'AG3004', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4327;
UPDATE public.course SET name = E'AG3005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4328;
UPDATE public.course SET name = E'AG3010', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4333;
UPDATE public.course SET name = E'AG3011', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4334;
UPDATE public.course SET name = E'AG3012', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4335;
UPDATE public.course SET name = E'AG3224', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4337;
UPDATE public.course SET name = E'AG4111', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4341;
UPDATE public.course SET name = E'AG5415', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4412;
UPDATE public.course SET name = E'LA9005', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4541;
UPDATE public.course SET name = E'LA9007', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4544;
UPDATE public.course SET name = E'FI1504', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4822;
UPDATE public.course SET name = E'AU5001', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4828;
UPDATE public.course SET name = E'AU5002', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4829;
UPDATE public.course SET name = E'MC4001', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4873;
UPDATE public.course SET name = E'MC4002', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4874;
UPDATE public.course SET name = E'MC4003', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4875;

-- table: study_plan_level_course
UPDATE public.study_plan_level_course SET is_active = FALSE, deactivated_at = NOW(), updated_at = NOW() WHERE id = ANY(ARRAY[1, 2, 91, 522, 1006, 1533, 6918, 8188, 9022, 9753, 9993]::BIGINT[]);

-- table: course_relation
INSERT INTO public.course_relation
  (id, study_plan_id, from_course_id, to_course_id, relation_type)
VALUES
  (86836, 52, 629, 1254, E'PREREQUISITE'),
  (86837, 164, 628, 1254, E'PREREQUISITE'),
  (86838, 165, 628, 1254, E'PREREQUISITE')
ON CONFLICT (study_plan_id, from_course_id, to_course_id, relation_type) DO NOTHING;
UPDATE public.course_relation SET is_active = FALSE, deactivated_at = NOW(), updated_at = NOW() WHERE id = ANY(ARRAY[3036, 3234, 4294, 4730, 5272, 6159, 8230, 8630, 8932, 11364, 11842, 11880, 13980, 15934, 15978, 16213, 19551, 19921, 20311, 20825, 20932, 22339, 25903, 27266, 27298, 27332, 27552, 35679, 36745, 37433, 37447, 42312, 46138, 46197, 47219, 48108, 48168, 51027, 51255, 51571, 53087, 55967, 56225, 57231, 57869, 60084, 62856, 63791, 64929, 64955, 65045, 67635, 68170, 69546, 70272, 70341, 73250, 73694, 74555, 75329, 78970, 79238, 79381, 79681, 82502, 83724, 83811, 83991, 85555, 86394]::BIGINT[]);

COMMIT;
